# Generated by Django 3.1 on 2023-07-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230704_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
    ]
