# Generated by Django 3.1 on 2023-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_billingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
