# Generated by Django 3.2 on 2023-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
