# Generated by Django 3.1 on 2023-07-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='return_reason',
            field=models.TextField(blank=True),
        ),
    ]
